layout_spectrum: 0.966193
typography_spectrum: 0.3600303
color:
  saturation: 0.46301
  lightness: 0.7113039
  brandStrength: 0.5589441
  rhythmicContrast: 0.4581858
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Seen
